name: CI

on: [push, pull_request]
jobs:
  industrial_ci:
    strategy:
      fail-fast: false
      matrix:
        env:
          - {CI_NAME: clang-format,
             OS_NAME: ubuntu,
             OS_CODE_NAME: bionic,
             ROS_DISTRO: melodic,
             BADGE: bionic,
             CLANG_FORMAT_CHECK: file,
             CLANG_FORMAT_VERSION: 8,
             }
          - {OS_NAME: ubuntu,
             OS_CODE_NAME: focal,
             ROS_DISTRO: foxy,
             ROSDEP_SKIP_KEYS: nvidia-cuda-dev,
             BADGE: bionic,
             TARGET_CMAKE_ARGS: "-DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs/",
             DOCKER_PULL: false,
             DOCKER_IMAGE: "schornakj/yak-1:focal-cuda11.0"}
          - {OS_NAME: ubuntu,
             OS_CODE_NAME: bionic,
             ROS_DISTRO: melodic,
             ROSDEP_SKIP_KEYS: nvidia-cuda-dev,
             BADGE: bionic,
             TARGET_CMAKE_ARGS: "-DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs/",
             DOCKER_PULL: false,
             DOCKER_IMAGE: "schornakj/yak_ci:bionic-cuda10.2"}
          - {OS_NAME: ubuntu,
             OS_CODE_NAME: bionic,
             ROS_DISTRO: melodic,
             ROSDEP_SKIP_KEYS: nvidia-cuda-dev,
             BADGE: bionic,
             TARGET_CMAKE_ARGS: "-DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs/",
             DOCKER_PULL: false,
             DOCKER_IMAGE: "schornakj/yak_ci:bionic-cuda9.2"}
          - {OS_NAME: ubuntu,
             OS_CODE_NAME: xenial,
             ROS_DISTRO: kinetic,
             ROSDEP_SKIP_KEYS: nvidia-cuda-dev libpcl-all-dev,
             BADGE: xenial,
             TARGET_CMAKE_ARGS: "-DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs/",
             DOCKER_PULL: false,
             DOCKER_IMAGE: "schornakj/yak-1:xenial-cuda10.2"}
          - {OS_NAME: ubuntu,
             OS_CODE_NAME: xenial,
             ROS_DISTRO: kinetic,
             ROSDEP_SKIP_KEYS: nvidia-cuda-dev libpcl-all-dev,
             BADGE: xenial,
             TARGET_CMAKE_ARGS: "-DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs/",
             DOCKER_PULL: false,
             DOCKER_IMAGE: "schornakj/yak-1:xenial-cuda9.2"}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
